<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Phaedros" name="InvocationNewsTest" tests="21" failures="3" timestamp="23 Feb 2020 23:00:23 GMT" time="9.779" errors="0">
  <testcase name="SearchBarMethod" time="0.003" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="math" time="0.002" classname="net.groot.data.InvocationNewsTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.NumberFormatException but got org.testng.TestException: 
Method InvocationNewsTest.math()[pri:0, instance:net.groot.data.InvocationNewsTest@50b494a6] should have thrown an exception of class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method InvocationNewsTest.math()[pri:0, instance:net.groot.data.InvocationNewsTest@50b494a6] should have thrown an exception of class java.lang.NumberFormatException
Method InvocationNewsTest.math()[pri:0, instance:net.groot.data.InvocationNewsTest@50b494a6] should have thrown an exception of class java.lang.NumberFormatException
	... 16 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- math -->
  <testcase name="math" time="0.001" classname="net.groot.data.InvocationNewsTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.NumberFormatException but got org.testng.TestException: 
Method InvocationNewsTest.math()[pri:0, instance:net.groot.data.InvocationNewsTest@50b494a6] should have thrown an exception of class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method InvocationNewsTest.math()[pri:0, instance:net.groot.data.InvocationNewsTest@50b494a6] should have thrown an exception of class java.lang.NumberFormatException
Method InvocationNewsTest.math()[pri:0, instance:net.groot.data.InvocationNewsTest@50b494a6] should have thrown an exception of class java.lang.NumberFormatException
	... 16 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- math -->
  <testcase name="math" time="0.003" classname="net.groot.data.InvocationNewsTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.NumberFormatException but got org.testng.TestException: 
Method InvocationNewsTest.math()[pri:0, instance:net.groot.data.InvocationNewsTest@50b494a6] should have thrown an exception of class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method InvocationNewsTest.math()[pri:0, instance:net.groot.data.InvocationNewsTest@50b494a6] should have thrown an exception of class java.lang.NumberFormatException
Method InvocationNewsTest.math()[pri:0, instance:net.groot.data.InvocationNewsTest@50b494a6] should have thrown an exception of class java.lang.NumberFormatException
	... 16 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- math -->
  <testcase name="invokeProvider" time="0.005" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="invokeProvider" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="invokeProvider" time="0.003" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="invokeProvider" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="invokeProvider" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="invokeProvider" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="mathError" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="mathError" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="mathError" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="mathError" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="mathError" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="mathError" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="mathError" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="mathError" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="mathError" time="0.001" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="mathError" time="0.0" classname="net.groot.data.InvocationNewsTest"/>
  <testcase name="webParameterTest" time="9.673" classname="net.groot.data.InvocationNewsTest"/>
</testsuite> <!-- InvocationNewsTest -->
